name: 'Terraform Pull Request'

on:
  push:
    branches:
    - dev

  pull_request:

jobs:  
  terraform_apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./setup  ########################please chnage folder name as per github repo####################
    needs: terraform
    environment:
      name: tf_apply  ########################please set environment secret in github repo settings and change name accordingly####################
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
        run: terraform apply
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
